# PRESENTACIÓN DE CERTIFICADOS (INDICANDO LOS DESBLOQUEADOS)
POST http://127.0.0.1:5001/certificado_routes/get_certificados_con_estado
Content-Type: application/json

{
    "id_usuario": 7
}
###

# CONSULTAR DETALLE DE UN CERTIFICADO
POST http://127.0.0.1:5001/certificado_routes/get_detalle_certificado
Content-Type: application/json

{
    "id_certificado": 1
}
###

# MARCAR CERTIFICADO COMO REVISADO
POST http://127.0.0.1:5001/certificado_routes/marcar_certificado_revisado
Content-Type: application/json

{
    "id_certificado": 8,
    "id_usuario": 7
}
###

# ENVIAR CERTIFICADO POR CORREO
POST http://127.0.0.1:5001/certificado_routes/enviar_certificado
Content-Type: application/json

{
    "id_certificado": 7,
    "id_usuario": 7,
    "username": "romero23",
    "plantilla_url": "https://lyhgavhtpjtnozoabwqk.supabase.co/storage/v1/object/public/recla-images/certificados/certificado1.png"
}
###

# PRESENTACIÓN DE CERTIFICADOS DESBLOQUEADOS POR UN USUARIO
POST http://127.0.0.1:5001/certificado_routes/get_certificados_desbloqueados_usuario
Content-Type: application/json

{
    "id_usuario": 7
}
###