# PRESENTACIÓN DE STICKERS (INDICANDO LOS DESBLOQUEADOS)
POST http://127.0.0.1:5001/sticker_routes/get_stickers_con_estado
Content-Type: application/json

{
    "id_usuario": 1
}
###

# DESBLOQUEAR STICKER
POST http://127.0.0.1:5001/sticker_routes/desbloquear_sticker
Content-Type: application/json

{
    "id_sticker": 6,
    "id_usuario": 7
}
###
